apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sharethepaws-pg
spec:
  instances: 2
  storage:
    size: 20Gi
  superuserSecret:
    name: sharethepaws-secrets
  bootstrap:
    initdb:
      database: sharethepaws
      owner: app
      secret:
        name: sharethepaws-secrets
  managed:
    roles:
      - name: app
        login: true
        superuser: false
        createdb: false
        createrole: false
